services:
  # Redis service for FSM, users, and temp storage
  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - studybuddybot-network-dev

  # Main bot application
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./bot.py:/app/bot.py
      - ./config.yaml:/app/config.yaml
      - ./src/locales:/app/src/locales
      - ./logs_test:/app/logs
      - ./media_test:/app/media
    ports:
      - "8001:8000"  # Different port to avoid conflict with prod
    environment:
      
      # Bot configuration environment
      - BOT_CONFIG=bot_test
      
      # Development flags
      - DEVELOPMENT=true
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for Redis to be ready...' &&
        while ! redis-cli -h redis ping > /dev/null 2>&1; do
          sleep 1
        done &&
        echo 'Redis is ready!' &&
        echo 'Starting bot in development mode...' &&
        python bot.py
      "
    restart: "no"
    networks:
      - studybuddybot-network-dev

networks:
  studybuddybot-network-dev:
    name: studybuddybot-network-dev
    driver: bridge
