services:
  # Redis service for FSM, users, and temp storage
  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly no
      --dir /data
      --dbfilename dump.rdb
      --save 60 1
    volumes:
      - ./redis_dump:/data
    restart: unless-stopped
    networks:
      - dev-network

  # Main bot application
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./bot.py:/app/bot.py
      - ./config.yaml:/app/config.yaml
      - ./src/locales:/app/src/locales
      - ./logs_test:/app/logs
      - ./media:/app/media
      - ./studybuddybot-471111-f80d6e34ca47.json:/app/studybuddybot-471111-f80d6e34ca47.json
    ports:
      - "8001:8000"  # Different port to avoid conflict with prod
    environment:
      - TZ=Europe/Moscow
      - BOT_CONFIG=bot_test
      - GOOGLE_APPLICATION_CREDENTIALS=/app/studybuddybot-471111-f80d6e34ca47.json
      - DEVELOPMENT=true
    command: >
      sh -c "
        echo '########################################################'
        echo 'Starting bot in development mode...' &&
        python bot.py
      "
    restart: "no"
    networks:
      - dev-network

networks:
  dev-network:
    name: dev-network
    driver: bridge
